### PR TITLE
Make the progress animation smoother

### LINKED ISSUE #1: Make the progress animation smoother
[Issuehunt badges](https://oss.issuehunt.io/r/sindresorhus/DockProgress/issues/1)

https://github.com/sindresorhus/DockProgress/blob/2fd7035c8c17e28b261efa04da91d3a6ad403cf2/Sources/DockProgress/DockProgress.swift#L40

Right now it only updates each time `progressValue` is updated or the NSProgress instance in `progress` changes. Let say you use this to update on each processed frame of a video, so the longer the video is, the smoother the progress animation is. That also means it will be pretty choppy on short clips.

Normally you would use a CALayer, which would animate between the progress events. This is however not possible for the Dock icon as we have to call `.display()` manually each time we want to update it. I tried to use CALayer and just capture an image of the layer 30 times a second, but it seems it's only possible to capture before or after the animation.

I think the solution is to simply implement the animation ourselves with an interval timer. We already have the previous progress and the current progress, so we can animate between them. It's a bit more complicated though as if we receive a new progress change while we're animation, we now need to animate to the new progress.

I'm also happy to consider other ideas.

I think we should also fade-in and fade-out the progress animation so it doesn't just suddenly appear at 0% and disappear at 100%.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [issuehunt issuehunt](https://oss.issuehunt.io/u/issuehunt) ($100.00)

### Submitted pull Requests
- [#9 Make the progress animation smoother](https://oss.issuehunt.io/r/sindresorhus/DockProgress/pull/9)
- [#18 Make the progress animation smoother](https://oss.issuehunt.io/r/sindresorhus/DockProgress/pull/18)
---

### Tips

- Checkout the [Issuehunt explorer](https://oss.issuehunt.io/r/sindresorhus/DockProgress/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://oss.issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by benkoska**
Fixes #1 

When you change the progress variable it schedules evenly spaces calls to change the animatedProgress variable. The animatedProgress variable then changes the previous progress and calls updateDockIcon()

public variables:
stepDuration - Default Value: 0.05 (5ms) - How long to wait between every "render"
totalSteps - Default Value: 30 - How many steps there should be between 0 to 1

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#1: Make the progress animation smoother](https://issuehunt.io/repos/123488065/issues/1)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by sindresorhus** [comment]
Did you try out your changes? Because this is what I'm seeing:

**Comment by benkoska** [comment]
I found the error. The problem is that the default step duration is higher than the speed with which the example app is increasing it at. The thing is that most apps don't go that fast and the 0.05 I have set are good for most normal apps.

**Comment by sindresorhus** [comment]
It should still be able to handle it though. App devs might set a certain step, but then it goes faster than they planned.

**Comment by sindresorhus** [comment]
Even after your workaround it's buggy for me and it sometimes resets.

**Comment by sindresorhus** [comment]
If I set:

```
Timer.scheduledTimer(withTimeInterval: 1, repeats: true) { _ in
			DockProgress.progress += 0.1
```

it should smoothly animate between the steps with easing, just like CALayer would. Now it animates hard and choppy.

**Comment by benkoska** [comment]
I will look into it.

**Comment by sindresorhus** [comment]
Friendly ping :)

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Pull request closed without merging**
